# See https://wiki.hyprland.org/Configuring/Binds/
unbind = Super, D
unbind = Super, M
unbind = Super, S
unbind = Super, X
unbind = Super, W
#!
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds
bind = Super, W, exec, floorp # Floorp
bind = Super, D, exec, vesktop # Discord
bind = Super, M, fullscreen, 1 # Maximize window
bind = Super, S, exec, steam # Steam
bind = Super, R, exec, /usr/lib/floorp/floorp --name floorp-2c243da8-5500-4e85-9d4d-6ea50c5728cf --profile /home/horia/.floorp/n447dc9t.default-release --start-ssb "{2c243da8-5500-4e85-9d4d-6ea50c5728cf}" # DeepSeek
bind = Super, Y, exec, /usr/lib/floorp/floorp --profile "/home/horia/.floorp/n447dc9t.default-release" --start-ssb "{ead3d9bb-d665-446a-9a3e-b4fecfa95a26}" # Youtube Music
bind = Super, Z, global, quickshell:mediaModeToggle # Media mode
bind = Super, X, exec, ~/.config/hypr/custom/scripts/openrgb.sh


# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above
